apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: logstash
  name: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: logstash
    spec:
      containers:
      - image: logstash
        name: logstash
        resources: {}
        imagePullPolicy: Never
status: {}
